### ISSUE TITLE
a8 fails to start with exeception for missing import module: psutil.error

### ISSUE THREAD

**Issue by hawkman69** [aliafshar/a8#20]
Followed the install steps as outlined on Unbuntu 14.04.  Upon startup a8 failes with exception; see traceback below.

From this stackoverflow [article](http://stackoverflow.com/questions/22529900/no-module-psutil-error) it seems psutil.error was removed in 2.0.0.

Removed import of psutil.error from a8 code and it started.  Not sure if others issues will be seen yet.

    Traceback (most recent call last):
    File "/usr/local/bin/a8", line 9, in <module>
     load_entry_point('a8==0.11', 'console_scripts', 'a8')()
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
      return ep.load()
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
      entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    File "/usr/local/lib/python2.7/dist-packages/a8/__main__.py", line 9, in <module>
      from a8 import app
    File "/usr/local/lib/python2.7/dist-packages/a8/app.py", line 12, in <module>
      from a8 import (terminals, files, buffers, vimembed, window, config, bookmarks,
    File "/usr/local/lib/python2.7/dist-packages/a8/terminals.py", line 11, in <module>
      import psutil, psutil.error
    ImportError: No module named error

**Comment by dbarnett** [comment]
Dupe of #11. You'll need to run from the git HEAD version for the time being.

**Comment by hawkman69** [comment]
Thanks.  I reviewed the open bugs before opening this one.  Did not think to check the closed bugs.

Note how many dupes you now have of bug 11.  Is there no plans to do a release or at least update README.md with correct install info?

**Comment by dbarnett** [comment]
Yeah, acknowledged. We need some volunteer contributors. Abominade is nominally maintained by two busy googlers, at least one of whom maintains a dozen other small projects…

**Comment by aliafshar** [comment]
I rolled a release from HEAD.
